### ISSUE TITLE
Sign In Flow

### ISSUE THREAD

**Issue by etonotieno** [jumadeveloper/AndelaTrackChallenge#7]
Hello @jumaallan , when a person tries to sign in to the app using their google account the app does not move to the next screen. The facebook option works however. This happens in Android 4.4.2.
 Another issue is that the Introductory pages keep showing up even after a person has logged in. Some code updates would be highly appreciated.

**Comment by jumaallan** [comment]
@CodeZilla7 
Now, the Google Sign In Fails because I deleted the project on Firebase. I reached the free limit, haha. You can however set up using your Firebase Credentials. It should work just fine. The issue with the splash screen showing every time is a shared preference issue. I'll fix that and update the code. But you can also do that if you get time and create a pull request 👍 Cheers

**Comment by etonotieno** [comment]
Okay, I will create a new Firebase project and see if I can solve the issues.
